#include <stdio.h>

int seed = 12345;

// this random func was generated by chatgpt :)
// Linear Congruential Generator (LCG) function using ints
int my_rand() {
	seed = (1664525 * seed + 1013904223) % 20;  // LCG formula (32-bit signed integer range)
	int i = 0;
	while(i < 16){
	       seed = seed * 2;	  
	       i = i + 1;
	}
	return seed;  // Return a pseudo-random number (shifting for a smaller range)
}

void array_print(int size, float arr[]){
	int i = 0;
	while(i < size){
		printf("arr[%d] = %f\n", i, arr[i]);
		i = i + 1;
	}
}

void array_init(int size, float arr[]){
	int i = 0;
	while(i < size){
		arr[i] = my_rand();
		i = i + 1;
	}
}

void bubble_sort(int size, float arr[]){
	int i = 0, j = 0, lim = 0, tmp = 0;
	while(i < size){
		lim = size - i - 1;
		j = 0;
		while(j < lim){
			if(arr[j] > arr[j + 1]){
				tmp = arr[j];
				arr[j] = arr[j + 1];
				arr[j + 1] = tmp;
			}
			j = j + 1;
		}
		i = i + 1;
	}
}

int main(void){
	float arr[10];

	array_init(10, arr);

	printf("Before sorting:\n");

	array_print(10, arr);

	printf("Applying bubble sort...\n");

	bubble_sort(10, arr);

	printf("After sorting:\n");

	array_print(10, arr);

	return 0;
}

